### PR TITLE
Add PreloadedOCIRootFSScheme constant

### PR DESCRIPTION
**Pull request by craigfurman**
See [Rep PR](https://github.com/cloudfoundry/rep/pull/15) for context.

### CODE REVIEW

**Comment by ematpl** [comment]
As discussed with the Garden team, let's plan to rename this to `preloaded+layer` or something similar to avoid introducing the CC-specific "droplet" term into Diego (which knows only about assets to download).

**Comment by craigfurman** [comment]
Changed name as discussed

**Comment by ematpl** [comment]
Thanks, @craigfurman !

**Comment by emalm** [comment]
Merged via https://github.com/cloudfoundry/bbs/commit/fe8e481a137734498654253e0030e89078c0ed11.

**Pull request closed without merging**
