### PR TITLE
Remove the `db/etcd` test suite from the bbs

### PR DESCRIPTION
**Pull request by elligoebel**
From the tracker comments: "We don't run these in CI any more, and as long as the migration tests pass, we're fulfilling our contract with regards to etcd. Let's remove these."

Tracker ID: #153885290

### CODE REVIEW

**Comment by emalm** [comment]
Hi, @elligoebel, thanks for the contribution! Before we incorporate the change, could you please submit a [CLA for yourself](http://cloudfoundry.org/pdfs/CFF_Individual_CLA.pdf), or alternatively publicize your membership in a GitHub organization associated with a corporate CLA? 

Thanks again,
Eric, CF Diego PM

**Comment by emalm** [comment]
Thanks, @elligoebel ! We'll coordinate with @christopherclark to ensure that the @cfdreddbot configuration is updated quickly after we receive the CLA. I'm guessing from the branch fork name that the CLA will authorize contributions from members of the [homedepot GitHub organization](https://github.com/homedepot), so if that's the case could you also please publicize your membership in that GitHub org?

Thanks again,
Eric

**Comment by elligoebel** [comment]
Hello, @emalm ! I've publicized my membership of the homedepot GitHub org and hopefully the CLA will be coming through shortly.

**Comment by emalm** [comment]
Hi, @elligoebel, thanks for the update! We'll continue to watch for the corporate CLA document.

Thanks again,
Eric

**Comment by emalm** [comment]
Hi, @elligoebel, any updates on whether that corporate CLA has been submitted? I haven't seen an update to the @cfdreddbot configuration yet.

Thanks again,
Eric

**Comment by elligoebel** [comment]
Hey @emalm, sorry it's taking so long. The corporate CLA is still being filled out on our end.

**Comment by emalm** [comment]
Thanks, @elligoebel ! We'll pull this in now that a CLA for you is on file.

Best,
Eric

**Comment by caod123** [comment]
Hi, @elligoebel ! I noticed in your commit that you removed the entire `db/etcd` folder rather than just the tests. Although we fully intend on doing that once we no longer support the migrations, we still need the code to pass our migration tests. For this story, we just want to remove the unit test files (any file matching `db/etcd/*_test.go` as well as the `db/etcd/test` helpers folder) since we no longer run these tests in our CI anyways.

Looking forward to hearing back from you,
Danny, CF Diego Engineer

**Comment by elligoebel** [comment]
Hi, @caod123 ! Sorry for the mistake,  I've corrected it to only remove the unit test files as well as the db/etcd/test  and  db/etcd/fakes folders.

Cheers,
Madeleine

**Comment by nimakaviani** [comment]
resolved conflicts and merged https://github.com/cloudfoundry/bbs/commit/8ca69e1bb149a1b13981a9044eb5c31292f6e3b2

**Pull request closed without merging**
